### ISSUE TITLE
Upstream tracking

### ISSUE THREAD

**Issue by physikerwelt** [physikerwelt/mathpipe#9]
- [x] brucemiller/LaTeXML#745
- [x] https://github.com/travis-ci/apt-package-whitelist/issues/2984
- [x] https://github.com/travis-ci/apt-package-whitelist/issues/2983
- [x] https://github.com/travis-ci/apt-package-whitelist/issues/2982
- [x] https://github.com/travis-ci/apt-package-whitelist/issues/2980
- [x] https://github.com/travis-ci/apt-package-whitelist/issues/3007
- [x] https://gerrit.wikimedia.org/r/#/c/284705/
